---
output: 
  html_document:
    includes:
      in_header: TheHTML.html
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(learnr)
knitr::opts_chunk$set(echo = FALSE)
```

``` {r DA_Quiz, echo = FALSE}
quiz(caption = "",
  question("Refer to the plot above, what kind of correlation is this?",
    answer("No correlation"),
    answer("Positive correlation"),
    answer("Negative correlation", correct = TRUE),
    allow_retry = TRUE,
    random_answer_order = TRUE
  ),
  question("Correlation coefficient can be used to measure strength of a nonlinear relationship.",
    answer("True", message = "We can use the correlation coefficient to measure the strength of a linear relationship between two variables, but not nonlinear relationship."),
    answer("False", correct = TRUE),
    allow_retry = TRUE,
    random_answer_order = TRUE
  ),
  question("Correlation between two variables implies a causal relationship.",
    answer("True", message = "Correlation does not imply causation."),
    answer("False", correct = TRUE),
    allow_retry = TRUE,
    random_answer_order = TRUE
  )
)
```

<div data-iframe-height></div>