---
output: 
  html_document:
    includes:
      in_header: TheHTML.html
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(learnr)
knitr::opts_chunk$set(echo = FALSE)
```

``` {r DW_Quiz, echo = FALSE}
quiz(caption = "Exercise",
  question("Which one of the following functions in the `dplyr` package allows us to see all of the variables (columns) at once, where several values of those columns are shown on the right of the variable names?",
    answer("`slice_head()`", message = "This function allows us to see just the first rows of the data."),
    answer("`slice_sample()`", message = "This function allows us to see a selection of random rows of the data."),
    answer("`slice_tail()`", message = "This function allows us to see the rows at the end of the data."),
    answer("`glimpse()`", correct = TRUE),
    allow_retry = TRUE,
    random_answer_order = TRUE
  ),
  question("Which one of the pipe operators (from the `magrittr` package) should be used right after a variable name if we want to perform a sequence of operations on that variable, and meanwhile, assign the final output to that variable (without redefining that variable using `<-` or `=`)?",
    answer("`%>%`", message = "This operator cannot assign the final output to that variable."),
    answer("`%<%`", message = "This is not a valie pipe operator."),
    answer("`%T>%`", message = "This is the side-effects operator."),
    answer("`%<>%`", correct = TRUE),
    allow_retry = TRUE,
    random_answer_order = TRUE
  ),
  question("Which of the following can the `mutate()` function in the `dplyr` package do? (more than one correct answers)",
    answer("Select certain variables(columns) of the data.", message = "Selecting certain variables(columns) of the data is the function of the `select()` function."),
    answer("Rename a variable.", message = "Renaming a variable is the function of the `rename()` function."),
    answer("Create a new variable.", correct = TRUE),
    answer("Modify an existing variable.", correct = TRUE),
    allow_retry = TRUE,
    random_answer_order = TRUE
  )
)
```

<div data-iframe-height></div>